#Please don't change it!
file-version: 1

#You can use mini messages to make it more interesting!

already_connected_message: you have already linked your discord account!

not_connected_message: you can't unlink your account because it's not connected!

hint_usage: you can type dc link or unlink to manage connect or disconnect discord account

expired_code_message: code has expired

connected_message: you have successfully connected your discord account

disconnected_message: you have successfully disconnected your discord account

click_message: 'CLICK ME!'

before_click_message: Click here to connect your account >>>>>

reload_message: Plugin has been reloaded!

no_permission: you don't have permission to use this command

#Database

#which driver you want to use MariaDB or MySQL(mariadb/mysql)?

driver: 'mysql'

database_address: 'database address'

database_port: 3306 #default port

database_name: 'database name'

#Username which will be used to connect to your database
username: ' '

#Password for the username
password: ' '

#Pools setting(advanced users usage only) I highly recommend to first understand what you're doing before changes!

#How much concurrent connection can plugin make with your database
MaximumPoolSize: 10

#How much idle concurrent connection can plugin make with your database for quicker read of data
MinimumIdle: 5

#How much time can idle connection exist before new one will be created
IdleTimeout: 150000

#How long can one connection exist before closing
MaxLifetime: 600000

#Time in seconds after code will no longer be valid
CodeExpirationTime: 120

#Set true if you want to have primary group and also default role such as player
DefaultRole: true

#Set to true if you want to leave previously connected user with theirs nickname
UserLeaveNickname: false

#List of roles that will be used in synchronization
#provide name of your roles set in luckperms and id of discord role that you would like to be set when user would connect his discord account

#base_role provides choice you can choose if you want to remove all roles from user that you wanted to sync
#or leave user with one base role that would be something like verified after all member of guild is verifed
#and isn't some kind of bot

RolesToSync:
  - base_role: 'id'
  - default: 'id'
# etc

SyncTimeOut: 120

#Guild
GuildId: ' your guild Id '

#bot token of your chosen application
BotToken: 'your bot token'


#Pick the authorization system you can either use Discord OAuth2 based system where you have to set up your api callbacks
#You have to know what are you doing in order to use such system also you have to connect to database on your own to change values in database
# It's more complicated than using simple in-game authentication but provides smoother feeling for users
# you can see more about it here and in plugin wiki
# https://discord.com/developers/applications/1538653202063298731/oauth2 https://docs.discord.com/developers/topics/oauth2

#Don't change the value unless you know what you're doing! better to stick with easier version if you don't feel fancy you also need to restart your server to change the mode!
DiscordOAuth2: false

DiscordApiBaseUrl: 'https://discord.com/api/oauth2/authorize?client_id='

#Redirect URL(URI) can be found on discord developer site and remember it must be one that's set on you're api application
RedirectUrl: 'only needed if youre going to use OAuth2'

#Client id of bot that performs actions after Redirect URL(URI) it can be id of application used in BotToken, although I strongly recommend creating another discord application
#as it doesn't cost you anything and doubles your bandwidth of api calls made to the discord.
ClientId: 'only needed if youre going to use OAuth2'

#Name of verification command on discord
VerifyName: ' desired name of the verify command '

#Description of verification command that will be used in discord command
VerifyDescription: ' '

#Name of the code variable that will be used in discord command
VerifyCodeVarName: ' '

#Description of the code variable that will be used in discord command
VerifyCodeVarDescription: ' '

#Name of the uuid variable that will be used in discord command
VerifyUUIDVarName: ' '

#Description of the uuid variable that will be used in discord command
VerifyUUIDVarDescription: ' '

#message that will be sent if there is no code
VerifyNoCode: ' '

#message that will be sent if code is invalid
VerifyInvalidCode: ' '

#message on success
VerifySuccessCode: ' '


