#Please don't change it!
file-version: 1

#tab completer for verification command that will be used for linking
connect: link

#tab completer for verification command that will be used for unlinking
disconnect: unlink

#You can use mini messages to make it more interesting!

#Message shown if player is already linked with dc account
already_connected_message: you have already linked your discord account!

#Message shown to player if he tried to unlink dc account, but they don't have it connected
not_connected_message: you can't unlink your account because it's not connected!

#Message shown to player that shows them how to use command
hint_usage: you can type dc link or unlink to manage connect or disconnect discord account

#Message shown to player if theirs code has just expired
expired_code_message: code has expired

#Message shown to player if something went wrong with connecting unlinking etc
error_code_message: something went wrong please contact server administrator

#Message shown to player after successfully linking dc account
connected_message: you have successfully connected your discord account

#Message shown to player after successfully unlinking dc account
disconnected_message: you have successfully disconnected your discord account

#Put here desired phrase to inform people that they need to click this part to open link or copy command with values
click_message: 'CLICK ME!'

#Part of message that will be presented before click_message
before_click_message: Click here to connect your account >>>>>

reload_message: Plugin has been reloaded!

#Message that will be shown if player doesn't have right permission to perform this command
no_permission: you don't have permission to use this command

#Database

#which driver you want to use MariaDB, MySQL or SQLITE(mariadb/mysql/sqlite) if string will be empty default will be used SQLITE?
#Also remember that you need mysql or sqlite if you want to use external web api
driver: ''

# 192.168.1.1, 127.0.0.1, mydatabase.org.pl
database_address: 'database address'

#default port 3306
database_port: 3306

#Name of the database that's going to be used
database_name: 'database name'

#Username which will be used to connect to your database
username: ' '

#Password for the username
password: ' '

#Pools setting(advanced users usage only) I highly recommend to first understand what you're doing before changes!
#How much concurrent connection can plugin make with your database
MaximumPoolSize: 10

#How much idle concurrent connection can plugin make with your database for quicker read of data
MinimumIdle: 5

#How much time can idle connection exist before new one will be created
IdleTimeout: 150000

#How long can one connection exist before closing
MaxLifetime: 600000

#Time in seconds after code will no longer be valid
CodeExpirationTime: 120

#Set true if you want to have primary group and also default role such as player
DefaultRole: true

#Set to true if you want to leave previously connected user with theirs nickname
UserLeaveNickname: false

#List of roles that will be used in synchronization
#provide name of your roles set in luckperms and id of discord role that you would like to be set when user would connect his discord account

#base_role provides choice you can choose if you want to remove all roles from user that you wanted to sync
#or leave user with one base role that would be something like verified after all member of guild is verifed
#and isn't some kind of bot

RolesToSync:
  - base_role: 'id'
    default: 'id'
# etc

#Guild
GuildId: ' your guild Id '

#bot token of your chosen application
BotToken: 'your bot token'

#Pick the authorization system you can either use Discord OAuth2 based system where you have to set up your api callbacks
#You have to know what are you doing in order to use such system also you have to connect to database on your own to change values in database
# It's more complicated than using simple in-game authentication but provides smoother feeling for users
# you can see more about it here and in plugin wiki
# https://discord.com/developers/applications/1538653202063298731/oauth2 https://docs.discord.com/developers/topics/oauth2

#Use DiscordOAuth2 or use discord command to verify
DiscordOAuth2: false

#Only activated if DiscordOAuth2 is set to true
#Don't change the value unless you know what you're doing! better to stick with easier version if you don't feel fancy you also need to restart your server to change the mode!
RedirectExternally: false

#Redirect URL(URI) can be found on discord developer site and remember it must be one that's set on you're api application
#URL has to be set to your minecraft ip(but remember https prefix is still necessary) or domain
RedirectUrl: 'only needed if youre going to use OAuth2'

#Change if you need to you can always use nginx reverse proxy etc.
WebApiHost: "127.0.0.1"

#Only activated if DiscordOAuth2 is set to true and RedirectExternally is set to false
#Port for your WebApi as it needs to be different from one that's being used by minecraft server
WebApiPort: 8888

#Client id of bot that performs actions after Redirect URL(URI).
ClientId: 'only needed if youre going to use OAuth2'

#Client secret of your app
ClientSecret: 'client secret app'

#Name of verification command on discord
VerifyName: ' desired name of the verify command '

#Description of verification command that will be used in discord command
VerifyDescription: ' '

#Name of the code variable that will be used in discord command
VerifyCodeVarName: ' '

#Description of the code variable that will be used in discord command
VerifyCodeVarDescription: ' '

#Name of the uuid variable that will be used in discord command
VerifyUUIDVarName: ' '

#Description of the uuid variable that will be used in discord command
VerifyUUIDVarDescription: ' '

#message that will be sent if there is no code
VerifyNoCode: ' '

#message that will be sent if code is invalid
VerifyInvalidCode: ' '

#message on success
VerifySuccessCode: ' '


